name: Continuous Integration
on: 
  push:
    branches:
      - main

  # Trigger on pull requests where the target branch is main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Dotnet Build
      run: dotnet build

    - name: Dotnet test
      run: dotnet build

    - name: npm install, test, lint
      run: |
           cd DotnetTemplate.Web
           echo "Run npm install"
           npm install 
           echo "Run npm test"
           npm t
           echo "Run npm lint"
           npm run lint